//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 malagis.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_STAUTS_COORD                101
#define IDS_STAUTS_COORD_TITLE          101
#define IDS_STAUTS_COORD_POS            102
#define IDS_PRJMANAGE                   103
#define IDS_STATUS_CURRENT_ACTION       104
#define IDS_STATUS_CURRENT_ACTION_CONTENT 105
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_malagisTYPE                 130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDB_BITMAP2                     311
#define IDB_BITMAP_POINTS_BAR           311
#define IDR_MENU_PRJ                    313
#define IDR_MENU_PRJ_FILE_CTRL          315
#define IDB_PRJ_VIEW                    317
#define IDB_BITMAP_TOOLS_ZOOM           318
#define IDC_CURSOR_HAND                 320
#define IDC_CURSOR_ZOOMIN               321
#define IDC_CURSOR_ZOOMOUT              322
#define IDB_BITMAP_LINES_BAR            324
#define IDB_BITMAP_PLOGON_BAR           325
#define ID_STATUS_COORD_TITLE           1000
#define ID_STATUS_COORD_POS             1001
#define ID_PRJMANAGE                    1002
#define ID_STATUS_CURRENT_ACTION        1003
#define ID_STATUS_CURRENT_ACTION_CONTENT 1004
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BUTTON_POINTS_INPUT          32771
#define ID_BUTTON2                      32772
#define ID_BUTTON_ZOOM_IN               32772
#define ID_CHECK_PRJ_MANAGE             32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_NEW_PRJ                      32776
#define ID_32777                        32777
#define ID_OPEN_PRJ                     32778
#define ID_PRJ_NEW_POINTS_FILE          32781
#define ID_32783                        32783
#define ID_32784                        32784
#define ID_32785                        32785
#define ID_32786                        32786
#define ID_32787                        32787
#define ID_PRJ_FILE_DISPLAY             32788
#define ID_PRJ_FILE_HIDE                32789
#define ID_PRJ_FILE_ACTIVE              32790
#define ID_PRJ_FILE_DEL                 32791
#define ID_PRJ_FILE_PRO                 32792
#define ID_PRJ_NEW_LINE_FILE            32795
#define ID_PRJ_NEW_POLY_FILE            32797
#define ID_PRJ_NEW_LABEL_FILE           32799
#define ID_32801                        32801
#define ID_PRJ_OPEN_FILE                32802
#define ID_BUTTON_ZOOMOUT               32803
#define ID_BUTTON_ZOOM_MOVE             32804
#define ID_BUTTON_ZOOM_REFRESH          32805
#define ID_BUTTON_ZOOM_RESET            32806
#define ID_BUTTON_POINTS_SELECT         32808
#define ID_BUTTON_POINTS_MOVE           32810
#define ID_BUTTON_POINTS_COPY           32811
#define ID_BUTTON_POINTS_CHANGE_PRO     32812
#define ID_BUTTON_POINTS_DELETE         32813
#define ID_BUTTON_POINTS_DELETE_ALL     32814
#define ID_BUTTON_LINES_INPUT           32820
#define ID_BUTTON_LINES_SELECT          32821
#define ID_BUTTON_LINES_COPY            32822
#define ID_BUTTON_LINES_MOVE            32823
#define ID_BUTTON_LINES_CHANGE_PRO      32824
#define ID_BUTTON_LINES_CUT             32825
#define ID_BUTTON_LINES_POINT_ADD       32826
#define ID_BUTTON_LINES_POINT_MOVE      32827
#define ID_BUTTON_LINES_POINT_DELETE    32828
#define ID_BUTTON_LINES_DELETE          32829
#define ID_BUTTON_LINES_DELETE_ALL      32830
#define ID_BUTTON_POLYGON_INPUT         32831

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        326
#define _APS_NEXT_COMMAND_VALUE         32832
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
